// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB85Xxr0CWP1qKKDjJQ1Vge70qVjB_otQ',
    appId: '1:1063482537337:web:6aab980a4e0a49bff96ba8',
    messagingSenderId: '1063482537337',
    projectId: 'bruma-2b5d9',
    authDomain: 'bruma-2b5d9.firebaseapp.com',
    storageBucket: 'bruma-2b5d9.firebasestorage.app',
    measurementId: 'G-8EF4Y2FKT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGTTpiK9qbqs6_4GMzJxsZb68Z6XqrfQU',
    appId: '1:1063482537337:android:28d33001653e6222f96ba8',
    messagingSenderId: '1063482537337',
    projectId: 'bruma-2b5d9',
    storageBucket: 'bruma-2b5d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgBGVuWs1Y4Z1H1XKPmi-AAC1C9Mb4gnM',
    appId: '1:1063482537337:ios:8681e2cbb56eede5f96ba8',
    messagingSenderId: '1063482537337',
    projectId: 'bruma-2b5d9',
    storageBucket: 'bruma-2b5d9.firebasestorage.app',
    iosBundleId: 'com.example.proyectoConMiCompa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgBGVuWs1Y4Z1H1XKPmi-AAC1C9Mb4gnM',
    appId: '1:1063482537337:ios:8681e2cbb56eede5f96ba8',
    messagingSenderId: '1063482537337',
    projectId: 'bruma-2b5d9',
    storageBucket: 'bruma-2b5d9.firebasestorage.app',
    iosBundleId: 'com.example.proyectoConMiCompa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB85Xxr0CWP1qKKDjJQ1Vge70qVjB_otQ',
    appId: '1:1063482537337:web:75b26fb3c895a981f96ba8',
    messagingSenderId: '1063482537337',
    projectId: 'bruma-2b5d9',
    authDomain: 'bruma-2b5d9.firebaseapp.com',
    storageBucket: 'bruma-2b5d9.firebasestorage.app',
    measurementId: 'G-3F4FQ3VXX1',
  );
}
